### ISSUE TITLE
Cannot find file: 'index.js' in ./src/Components/Home/Index.js

### ISSUE THREAD

**Issue by Galaeno** [alkemyTech/OT130-CLIENT#129]
![image](https://user-images.githubusercontent.com/14810649/156457452-14947b42-97b0-4aa5-9123-382a85712492.png)

Cambiar nombre del archivo src/Components/Home/Index.js a src/Components/Home/index.js, con minuscula

**Comment by RodrigoM10** [comment]
Listo solucionado bug.
