### ISSUE TITLE
Error al querer editar un usuario

### ISSUE THREAD

**Issue by facundocolavini** [alkemyTech/OT130-CLIENT#143]
Al ir al listado de usuarios y querer editar un usuario no edita correctamente y no manda los cambios nuevos.
![image](https://user-images.githubusercontent.com/54385792/156700758-d15bcc2b-b468-4eeb-ba8b-cc77ff55d468.png)

**Comment by mateolewinzon** [comment]
Solucioné esos warnings, pero lo del error de network es un error de la api. Cuando se usa Put (como hay que hacer segun los docs de la api) tira 422 de que el email ya fue registrado (no tiene sentido, estamos editando usuario). Cuando se usa Patch tira el error de cors. Es un problema de API.
