### ISSUE TITLE
Error al renderizar data en BackOffice de Organización 

### ISSUE THREAD

**Issue by facundocolavini** [alkemyTech/OT130-CLIENT#145]
Al entrar a  backoffice/organization la data no es renderizada correctamente.
Esto se puede solucionar agregando data.data en el Componente de Organización o llamando a el estado de redux en el componente.

![image](https://user-images.githubusercontent.com/54385792/156701439-1ab9dec7-3579-41a3-9dd2-7e3487f0741c.png)

**Comment by RodrigoM10** [comment]
@facundocolavini  ahi me encargo de este issue

**Comment by facundocolavini** [comment]
Se cierra corrigiendo el renderizado de organization.
