### ISSUE TITLE
Implementar Componente de mensage Error o Success con temporizador

### ISSUE THREAD

**Issue by facundocolavini** [alkemyTech/OT130-CLIENT#28]
Realizar un componente que reciba por props un timer un mensaje y se encargue con su propia lógica de mostrar un mensaje en el tiempo que se le envió.

Alternativas: Utilizar sweetAlert 
https://sweetalert2.github.io/

**Comment by Galaeno** [comment]
Se cierra por duplicado -> https://github.com/alkemyTech/OT130-CLIENT/issues/37
