### ISSUE TITLE
Cambiar el post por get en la función Get del privateApiService

### ISSUE THREAD

**Issue by IgAgg** [alkemyTech/OT130-CLIENT#49]
Me equivoqué editando el metodo Get y lo dejé utilizando un post en vez de get. Hay que cambiar el `instance.post` por `instance.get`
![image](https://user-images.githubusercontent.com/99047430/152606068-68e3153b-ec58-4053-b3eb-3f39f27815dd.png)

**Comment by Galaeno** [comment]
@IgAgg le agregaría una descripción de por qué este issue

**Comment by IgAgg** [comment]
@Galaeno listo
